(ns vpn-kis-bb.domain.split
  "Pure: split-tunnel config validation + artifact text generators.

   Bash equivalent: `split_*` family in vpn-firewall-setup.sh.

   Side-effecting writers live in the adapters; this namespace only
   produces strings and validated data."
  (:require [clojure.string :as str]))

(def default-table     142)
(def default-mark      "0x42")
(def mangle-chain      "VPNKIS-SPLIT")
(def conf-dir          "/etc/vpn-killswitch/split")
(def dnsmasq-dir       "/etc/dnsmasq.d")

(defn ipset-name       [n] (str "vpnkis_split_" n "_dst"))
(defn unit-name        [n] (str "vpn-killswitch-split-" n ".service"))
(defn unit-path        [n] (str "/etc/systemd/system/" (unit-name n)))
(defn dnsmasq-path     [n] (str dnsmasq-dir "/vpn-kis-split-" n ".conf"))
(defn up-script-path   [n] (str conf-dir "/" n ".up.sh"))
(defn down-script-path [n] (str conf-dir "/" n ".down.sh"))
(defn conf-path        [n] (str conf-dir "/" n ".conf"))

(def valid-name-re #"^[a-zA-Z0-9_-]+$")

(defn validate
  "Validate + normalize a split config map.

   Input expected shape:
     {:name        \"funeraria\"
      :domains     [\"*.funerariafrancana.com.br\"]
      :dev         \"tun-funeraria\"
      :table       142
      :mark        \"0x42\"
      :priority    :auto                ; or an integer
      :ovpn-config \"/path/to.ovpn\"}   ; optional, for `split connect`

   Returns Result-shaped:
     {:ok? true  :value <normalized>}
     {:ok? false :error <msg>}."
  [{:keys [name domains dev table mark priority ovpn-config] :as in}]
  (cond
    (nil? in)
    {:ok? false :error "split config is nil"}

    (not (string? name))
    {:ok? false :error "split: :name must be a string"}

    (not (re-matches valid-name-re name))
    {:ok? false :error (str "split: :name must match " valid-name-re)}

    (or (nil? domains) (empty? domains))
    {:ok? false :error "split: :domains must be non-empty"}

    (not (string? dev))
    {:ok? false :error "split: :dev must be a string (matches openvpn --dev)"}

    :else
    (let [doms (mapv (fn [d]
                       (-> (str d)
                           str/trim
                           (str/replace #"^\*\." "")))
                     domains)]
      {:ok? true
       :value {:name        name
               :domains     doms
               :dev         dev
               :table       (or table default-table)
               :mark        (or mark default-mark)
               :priority    (or priority :auto)
               :ovpn-config ovpn-config}})))

(defn dnsmasq-drop-in-text
  "Generate the dnsmasq drop-in for a validated split config.
   One `ipset=/<domain>/<set>` line per domain. Leading `*.` already stripped."
  [{:keys [name domains]}]
  (let [set (ipset-name name)]
    (str "# Generated by vpn-kis-bb split add " name "\n"
         "# Domains routed via auxiliary tunnel\n"
         (str/join "\n"
                   (for [d domains]
                     (str "ipset=/" d "/" set)))
         "\n")))

(defn openvpn-up-script-text
  [{:keys [name dev table]}]
  (str "#!/bin/sh\n"
       "# openvpn --up hook for split '" name "'.\n"
       "set -eu\n"
       "DEV=\"${1:-" dev "}\"\n"
       "ip route replace default dev \"$DEV\" table " table "\n"
       "logger -t vpn-kis-split \"[" name "] route table " table " -> $DEV\"\n"))

(defn openvpn-down-script-text
  [{:keys [name table]}]
  (str "#!/bin/sh\n"
       "# openvpn --down hook for split '" name "'.\n"
       "set -eu\n"
       "ip route flush table " table " 2>/dev/null || true\n"
       "logger -t vpn-kis-split \"[" name "] route table " table " flushed\"\n"))

(defn systemd-unit-text
  "Boot-persistence oneshot. Hydrates the ipset, mangle hookup, and ip rule.
   Stop hook tears them down."
  [{:keys [name table mark priority]}]
  (let [set (ipset-name name)
        ch  mangle-chain]
    (str
     "[Unit]\n"
     "Description=VPN Kill-Switch — split '" name "' (mark " mark " -> table " table ")\n"
     "After=network-pre.target\n"
     "Before=network.target\n"
     "\n"
     "[Service]\n"
     "Type=oneshot\n"
     "RemainAfterExit=yes\n"
     "ExecStart=/sbin/ipset create " set " hash:ip family inet hashsize 1024 maxelem 65536 timeout 3600 -exist\n"
     "ExecStart=-/sbin/iptables -t mangle -N " ch "\n"
     "ExecStart=/bin/sh -c '/sbin/iptables -t mangle -C OUTPUT -j " ch " 2>/dev/null || /sbin/iptables -t mangle -A OUTPUT -j " ch "'\n"
     "ExecStart=/bin/sh -c '/sbin/iptables -t mangle -C PREROUTING -j " ch " 2>/dev/null || /sbin/iptables -t mangle -A PREROUTING -j " ch "'\n"
     "ExecStart=/bin/sh -c 'while /sbin/iptables -t mangle -D " ch " -m set --match-set " set " dst -j MARK --set-mark " mark " 2>/dev/null; do :; done'\n"
     "ExecStart=/sbin/iptables -t mangle -A " ch " -m set --match-set " set " dst -j MARK --set-mark " mark "\n"
     "ExecStart=/bin/sh -c 'while /sbin/ip rule del priority " priority " 2>/dev/null; do :; done'\n"
     "ExecStart=/sbin/ip rule add fwmark " mark " lookup " table " priority " priority "\n"
     "ExecStop=/bin/sh -c 'while /sbin/ip rule del priority " priority " 2>/dev/null; do :; done'\n"
     "ExecStop=-/sbin/iptables -t mangle -D " ch " -m set --match-set " set " dst -j MARK --set-mark " mark "\n"
     "ExecStop=-/sbin/ip route flush table " table "\n"
     "\n"
     "[Install]\n"
     "WantedBy=multi-user.target\n")))
