(ns vpn-kis-bb.domain.split-test
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.string :as str]
            [vpn-kis-bb.domain.split :as s]))

(def good-cfg
  {:name "example"
   :domains ["*.example.com" "app.example.org"]
   :dev "tun-example"})

(deftest validate-test
  (testing "happy path"
    (let [r (s/validate good-cfg)]
      (is (:ok? r))
      (is (= ["example.com" "app.example.org"] (:domains (:value r))))
      (is (= s/default-table (:table (:value r))))
      (is (= s/default-mark (:mark (:value r))))
      (is (= :auto (:priority (:value r))))))
  (testing "missing name"
    (is (not (:ok? (s/validate (dissoc good-cfg :name))))))
  (testing "bad name chars"
    (is (not (:ok? (s/validate (assoc good-cfg :name "bad name"))))))
  (testing "empty domains"
    (is (not (:ok? (s/validate (assoc good-cfg :domains [])))))))

(deftest dnsmasq-drop-in-test
  (let [v (:value (s/validate good-cfg))
        out (s/dnsmasq-drop-in-text v)]
    (is (str/includes? out "ipset=/example.com/vpnkis_split_example_dst"))
    (is (str/includes? out "ipset=/app.example.org/vpnkis_split_example_dst"))
    (is (str/includes? out "# Generated by vpn-kis-bb split add example"))))

(deftest up-down-scripts-test
  (let [v (:value (s/validate good-cfg))
        up (s/openvpn-up-script-text v)
        down (s/openvpn-down-script-text v)]
    (is (str/starts-with? up "#!/bin/sh"))
    (is (str/includes? up "ip route replace default dev"))
    (is (str/includes? up "table 142"))
    (is (str/includes? down "ip route flush table 142"))))

(deftest systemd-unit-test
  (let [v (:value (s/validate (assoc good-cfg :priority 5089)))
        body (s/systemd-unit-text v)]
    (is (str/includes? body "[Unit]"))
    (is (str/includes? body "Description=VPN Kill-Switch"))
    (is (str/includes? body "ExecStart=/sbin/ipset create vpnkis_split_example_dst"))
    (is (str/includes? body "ExecStart=/sbin/ip rule add fwmark 0x42 lookup 142 priority 5089"))
    (is (str/includes? body "ExecStop="))))

(deftest path-helpers-test
  (is (= "vpnkis_split_foo_dst" (s/ipset-name "foo")))
  (is (= "vpn-killswitch-split-foo.service" (s/unit-name "foo")))
  (is (= "/etc/dnsmasq.d/vpn-kis-split-foo.conf" (s/dnsmasq-path "foo"))))
