(ns vpn-kis-bb.adapters.firewall-ufw
  "UfwFirewall — IFirewallBackend impl. Applies a rule plan generated by
   `domain.rules/before-rules-text` to UFW.

   Apply sequence (mirrors the bash original):
     1. ufw --force reset
     2. set default deny in/out/routed
     3. ufw allow in/out on lo
     4. write /etc/ufw/before.rules (from the pure generator)
     5. write /etc/ufw/before6.rules (drop-all v6 — IPv4-only design)
     6. ufw --force enable
     7. ufw reload

   Snapshot/restore is a directory copy of /etc/ufw/*.rules + defaults."
  (:require [babashka.fs :as fs]
            [hive-dsl.result :as r]
            [hive-system.protocols :as proto]
            [vpn-kis-bb.domain.rules :as rules]
            [vpn-kis-bb.ports.firewall :as port]))

(def before-rules-path  "/etc/ufw/before.rules")
(def before6-rules-path "/etc/ufw/before6.rules")

(def before6-text
  "*filter
:ufw6-before-input - [0:0]
:ufw6-before-output - [0:0]
:ufw6-before-forward - [0:0]
-A ufw6-before-input -j DROP
-A ufw6-before-output -j DROP
-A ufw6-before-forward -j DROP
COMMIT
")

(defn- run [shell cmd]
  (let [resp (proto/shell-exec! shell cmd {:timeout-ms 60000})]
    (cond
      (r/err? resp)              resp
      (zero? (-> resp :ok :exit)) (r/ok (:ok resp))
      :else                      (r/err :ufw/non-zero-exit (:ok resp)))))

(defn- run-> [acc shell cmd]
  (if (r/err? acc) acc (run shell cmd)))

(defrecord UfwFirewall [shell write-fn read-fn]
  port/IFirewallBackend
  (-backend-id [_] :ufw)

  (-snapshot [_]
    (let [paths [before-rules-path before6-rules-path
                 "/etc/ufw/user.rules" "/etc/ufw/user6.rules"
                 "/etc/ufw/after.rules" "/etc/default/ufw"]
          captured (reduce (fn [acc p]
                             (let [r (read-fn p)]
                               (assoc acc p (when (r/ok? r) (:ok r)))))
                           {} paths)]
      (r/ok {:files captured :at (java.time.Instant/now)})))

  (-apply-rules! [_ rule-plan {:keys [dry-run? skip-reset?]}]
    (let [before-txt (rules/before-rules-text rule-plan)]
      (if dry-run?
        (r/ok {:dry-run? true
               :before-rules before-txt
               :before6-rules before6-text})
        (-> (r/ok :start)
            ((fn [acc] (if skip-reset? acc (run-> acc shell ["ufw" "--force" "reset"]))))
            (run-> shell ["ufw" "default" "deny" "incoming"])
            (run-> shell ["ufw" "default" "deny" "outgoing"])
            (run-> shell ["ufw" "default" "deny" "routed"])
            (run-> shell ["ufw" "allow" "in" "on" "lo"])
            (run-> shell ["ufw" "allow" "out" "on" "lo"])
            ((fn [acc]
               (if (r/err? acc) acc (write-fn before-rules-path before-txt))))
            ((fn [acc]
               (if (r/err? acc) acc (write-fn before6-rules-path before6-text))))
            (run-> shell ["ufw" "--force" "enable"])
            (run-> shell ["ufw" "reload"])))))

  (-restore! [_ snapshot]
    (let [files (:files snapshot)]
      (doseq [[p body] files :when body]
        (write-fn p body))
      (run shell ["ufw" "reload"])))

  (-reload! [_]
    (run shell ["ufw" "reload"])))

(defn- default-write [path body]
  (try
    (fs/create-dirs (fs/parent path))
    (spit path body)
    (r/ok {:path path :bytes (count body)})
    (catch Throwable t
      (r/err :ufw/write-failed {:path path :cause (str t)}))))

(defn- default-read [path]
  (try
    (if (fs/exists? path)
      (r/ok (slurp path))
      (r/err :ufw/no-file {:path path}))
    (catch Throwable t
      (r/err :ufw/read-failed {:path path :cause (str t)}))))

(defn make
  ([shell] (make shell {}))
  ([shell {:keys [write-fn read-fn]
           :or   {write-fn default-write
                  read-fn  default-read}}]
   (->UfwFirewall shell write-fn read-fn)))
